### PR TITLE
Added multiple icons

### PR DESCRIPTION
**Pull request by feedmes1eep**
Made icons for BlueStacks, Ookla SpeedTest, Parsec, Valorant, WSL Ubuntu, HexChat, MEGA, NoxPlayer, Soundpad, Thonny and Viber.

Changed informations line for the Filezilla config file.

PS: Most of the icons i'll be contributing will be transparent unless someone asks for Black and white. :D

### CODE REVIEW

**Comment by PinkDev1** [comment]
Looks good. 
But I have to ask: @feedmes1eep why did you remove the comment that indicates on wich line the program path should be changed?

**Comment by feedmes1eep** [comment]
@PinkDev1 ohh sorry, my bad. I forgot to include that in the script that makes the config files for me xd 
Should i add it and then pull request again?

**Comment by Ruben35** [comment]
Yes, you should push the new changes and then, make a new pull request

**Comment by feedmes1eep** [comment]
Alright, will do.

**Pull request closed without merging**
